version: '3'
services:
  www:
    build: .
    image: magento:1.9.3.7
    command: ["/var/www/bin/install"]
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    env_file:
      - default.env