version: '2'
services:
  php:
    build: .
    command: -- bin/install
    mem_limit: 4096m
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql
    entrypoint: bin/wait-for-it mysql:3306
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: www
      MYSQL_ROOT_PASSWORD: root