version: '3'
services:
  www:
    build: .
    image: magento:2.2.5
    command: ["/var/www/bin/install"]
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    env_file:
      - default.env
